// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuOEL4hotsr86ZT07DQmEbYT0pbBJc0ro',
    appId: '1:891402757862:web:38e32c8bd2496806c6fd27',
    messagingSenderId: '891402757862',
    projectId: 'fonisquiz-oday24',
    authDomain: 'fonisquiz-oday24.firebaseapp.com',
    storageBucket: 'fonisquiz-oday24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTw7rLMcIeT1E0GZlWitQBUieQvhOkgrM',
    appId: '1:891402757862:android:a563022332896e55c6fd27',
    messagingSenderId: '891402757862',
    projectId: 'fonisquiz-oday24',
    storageBucket: 'fonisquiz-oday24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-FjI1WWKg0_afviXIaSCaafRj3pAOcbQ',
    appId: '1:891402757862:ios:6094cce36446daf8c6fd27',
    messagingSenderId: '891402757862',
    projectId: 'fonisquiz-oday24',
    storageBucket: 'fonisquiz-oday24.appspot.com',
    iosBundleId: 'com.example.fonisOpenday24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-FjI1WWKg0_afviXIaSCaafRj3pAOcbQ',
    appId: '1:891402757862:ios:6094cce36446daf8c6fd27',
    messagingSenderId: '891402757862',
    projectId: 'fonisquiz-oday24',
    storageBucket: 'fonisquiz-oday24.appspot.com',
    iosBundleId: 'com.example.fonisOpenday24',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuOEL4hotsr86ZT07DQmEbYT0pbBJc0ro',
    appId: '1:891402757862:web:b9166704ab0f0273c6fd27',
    messagingSenderId: '891402757862',
    projectId: 'fonisquiz-oday24',
    authDomain: 'fonisquiz-oday24.firebaseapp.com',
    storageBucket: 'fonisquiz-oday24.appspot.com',
  );
}
